Dashboard Overview
Processillustrering/Processillustrering pull request #102
Opened 2022-05-11 08:46 UTC by Caw3

Old upload page for setting to localstorage is still reachable at /test/upload.

2022-05-11 11:12 UTC, JoXW100 requested changes

2022-05-11 11:12 UTC, JoXW100 commented on src/components/dashboard/dividerStack.js
> +}))
should be moved to a separate file, or into the function body

2022-05-11 11:12 UTC, JoXW100 commented on src/components/dashboard/dividerStack.js
> +export default function DividerStack () {
be consistent and use other function declaration method

2022-05-11 11:12 UTC, JoXW100 commented on src/components/dashboard/dividerStack.js
> +import { styled } from '@mui/material/styles'
No need to import react like this
```suggestion
import Divider from '@mui/material/Divider'
import Typography from '@mui/material/Typography'
import Paper from '@mui/material/Paper'
import Stack from '@mui/material/Stack'
import { styled } from '@mui/material/styles'
```

2022-05-11 11:12 UTC, JoXW100 commented on src/components/dashboard/uploadButton.js
> +import styles from '../../styles/dashboardStyles.module.css'
No need to import react like this
```suggestion
import IconButton from '@mui/material/IconButton'
import AddCircleOutlinedIcon from '@mui/icons-material/AddCircleOutlined'
import styles from '../../styles/dashboardStyles.module.css'
```

2022-05-11 11:12 UTC, JoXW100 commented on src/styles/dashboardStyles.module.css
> +
Strange indentation in this file

2022-05-11 11:12 UTC, JoXW100 commented on src/utils/localStorage.js
Remove debug functions in this file, (all `console.log`)

2022-05-11 11:12 UTC, JoXW100 commented on test/database.test.js
> +    expect(conn.find).toHaveBeenCalledWith(testQuery,{})
consider using a default value in this function

2022-05-11 12:41 UTC, Caw3 commented on test/database.test.js
> +    expect(conn.find).toHaveBeenCalledWith(testQuery,{})
I do not understand. The function needs a specific value?

2022-05-11 12:42 UTC, Caw3 commented on src/components/dashboard/dashSearchField.js
> +}))
This should be refactored later together with the identical components in navigationBar.js

2022-05-11 12:53 UTC, JoXW100 approved these changes

2022-05-11 13:38 UTC, thomssonkarl commented on src/components/dashboard/dashAlert.js
> +    <Collapse in={!!alertOpen}>
so just alterOpen? (!!)

2022-05-11 13:38 UTC, thomssonkarl commented on src/components/dashboard/dashAlert.js
> +          {alertOpen}
'alertOpen' is quite confusing, usually we use xOpen for open/close states but this seems like it is some text.

2022-05-11 13:38 UTC, thomssonkarl commented on src/components/dashboard/dividerStack.js
> +export default function DividerStack () {
Agreed keep it the same as the rest

2022-05-11 13:38 UTC, thomssonkarl commented on src/components/dashboard/loginGroup.js
> +          id='menu-appbar'
Id can be removed here if not used

2022-05-11 13:38 UTC, thomssonkarl commented on src/pages/index.js
> +      console.log('session was checked')
This should probably not be in production? (console.log)

2022-05-12 06:21 UTC, thomssonkarl approved these changes

2022-05-12 07:54 UTC, merged