Categories for dashboard and general documents in dashboard view
Processillustrering/Processillustrering pull request #109
Opened 2022-05-17 10:34 UTC by Caw3

fixes #106 

![Selection_016](https://user-images.githubusercontent.com/4652849/168792006-172ef8e1-9a82-46f6-9351-d004e78432af.png)
![Selection_015](https://user-images.githubusercontent.com/4652849/168792009-01e129bf-d9f3-46ce-9c03-5b874496d8f6.png)

2022-05-17 12:36 UTC, JoXW100 requested changes
Many components should be moved to separate files, documentation (types) are lacking.

2022-05-17 12:36 UTC, JoXW100 commented on src/components/dashboard/dashAlert.js
> +  })
add dependacy
```suggestion
  useEffect(() => {
    if (!alertOpen) { return }
    const timeId = setTimeout(() => {
      setAlertOpen(null)
    }, 2000)
    return () => {
      clearTimeout(timeId)
    }
  }, [alertOpen])
```

2022-05-17 12:57 UTC, Caw3 commented on src/components/dashboard/dashUploadDialog.js
> +    }
Needs to be able to handle an object without the documents field i.e there is a control flow

2022-05-17 13:20 UTC, Caw3 commented on src/components/dashboard/graphCard.js
> +  }
Why? That would only make it more of pain to work with than it already is. I can understand if there is any substantial subfuntions but this would just be annoying

2022-05-17 14:32 UTC, JoXW100 commented on src/components/dashboard/graphCard.js
> +  }
It is a code standard that components are located in their own files names the same as the component itself.

2022-05-17 14:40 UTC, JoXW100 requested changes
Some issues have been fixed but moving components to separate files and some other issues remain.

2022-05-17 15:39 UTC, JoXW100 commented on src/components/dashboard/dashUploadDialog.js
> +    }
May be true, however the boolean operators && and || still operate this way, see: https://cdmckay.org/eager-boolean-operators-in-javascript

2022-05-17 17:56 UTC, thomssonkarl approved these changes
Some small things pointed out

2022-05-17 17:56 UTC, thomssonkarl commented on src/components/dashboard/dashCategory.js
> +            key={index} elem={elem}
New line

2022-05-17 17:56 UTC, thomssonkarl commented on src/components/dashboard/dashUploadFormDocument.js
> +    <div sx={{ display: 'inline-block' }}>
Dead code? Sx prop is not a thing for divs right?

2022-05-18 09:47 UTC, JoXW100 approved these changes

2022-05-18 09:48 UTC, merged