npm scripts for ESlint and standardjs and github workflow
Processillustrering/Processillustrering pull request #11
Opened 2022-03-24 20:20 UTC by Caw3

Commands:

```
- npm install, install dependencies
- npm run lint, runs Eslint (web vitals) and Standardjs linter
- npm run format, formats all files in the directory according to the standardjs style guide
```

The github workflow script works by calling npm run lint on every new pull request, returning any errors found.
Note that the github workflow does **not** autoformat anything andt herefore npm run format should be used **before** submitting a pull request.

Standardjs style guide can be found [here](https://standardjs.com).

2022-03-26 14:12 UTC, JoXW100 reviewed
Unsure why the the component name in the index.js file was changed, seams unrelated to the issue and might cause problems.

2022-03-26 14:12 UTC, JoXW100 commented on src/pages/index.js
> +const main = () =>
This change seams unrelated to the issue and causes a name conflict with the already defined `main` component.

2022-03-26 14:58 UTC, Caw3 commented on src/pages/index.js
> +const main = () =>
This is from 4f557f6f56179de6b958c8f51ebfac97265578e7 that fixes the following ESlint output:

 ./src/pages/index.js
4:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export
4:[16](https://github.com/Processillustrering/Processillustrering/runs/5682695471?check_suite_focus=true#step:4:16)  Error: Component definition is missing display name  react/display-name

There won't be any naming conflicts since it is exported as the default:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

2022-03-26 16:23 UTC, JoXW100 commented on src/pages/index.js
> +const main = () =>
Ah i see, however it should still a component and should follow such naming convention, `main` is a builtin component used in that very component, calling it `Main` (start with capital letter) or something else would be fine.

2022-03-26 16:34 UTC, Caw3 commented on src/pages/index.js
> +const main = () =>
I agree

2022-03-26 16:35 UTC, JoXW100 requested changes
Rename the component to start with a capital letter such as `Main`.

2022-03-27 00:18 UTC, thomssonkarl approved these changes

2022-03-27 07:40 UTC, merged