First implementation of dialog popup information window
Processillustrering/Processillustrering pull request #31
Opened 2022-04-06 16:17 UTC by thomssonkarl

Implemented first version of dialog window. Currently this supports clicking activity nodes and getting a dialog window to popup. This is currently using hardcoded mockup data. 

To implement in future iterations: 
- Tabs should update the content of the window (when we know what should be here)
- Windows should be able to take information from its given connections (display valuebox text etc)
<img width="1020" alt="Screenshot 2022-04-06 at 18 17 04" src="https://user-images.githubusercontent.com/61412812/162020716-32fd7939-4378-45c0-a257-00e06fa0660a.png">

2022-04-07 12:26 UTC, JoXW100 requested changes
The main problem is that components are added as child components to `ActivityNode`, there should instead be a single global popup component accessed through the context. This ensures only one popup is open at the same time and reduces bloat.

2022-04-07 12:26 UTC, JoXW100 commented on src/components/diagram/customNodes/activityNode.js
> +      ) : null}
Two issues, firstly why is the `DialogPopup` added as a child to the activity node? This should not be the case since only one popup dialog should be open at a one time, this adds unnecessary bloat the the activity node.
Secondly there is no need to add / remove the component if it is open or not, the `open` prop allows the component itself to keep track of this.

2022-04-07 12:26 UTC, JoXW100 commented on src/components/dialogPopup.js
> +function DialogPopup (props) {
extract relevant props to be consistent with the other components

2022-04-07 12:26 UTC, JoXW100 commented on src/components/dialogPopup.js
> +        </DialogActions>
Why is the `dialogPopup` content hard coded like this? A popup component generally should be constructed from some input prop

2022-04-07 12:26 UTC, JoXW100 commented on src/components/nestedList.js
> +  ];
This should be extracted as a separate file that is passed as a prop to the function

2022-04-07 12:26 UTC, JoXW100 commented on src/components/nestedList.js
> +function NestedList() {
be consistent with component declarations,
```suggestion
const NestedList = () => {
```

2022-04-07 12:26 UTC, JoXW100 commented on src/components/nestedList.js
> +import ExpandMore from "@mui/icons-material/ExpandMore";
when importing this many components from the same library its better to import a parent and access the component from it. Eg: `import Material from "@mui/material"` and then use `Material.List`

2022-04-07 12:26 UTC, JoXW100 commented on src/styles/activityNode.module.css
> +    cursor:pointer;
indentation

2022-04-07 12:54 UTC, thomssonkarl commented on src/components/dialogPopup.js
> +        </DialogActions>
Not sure what you are getting at here, all dialogs will have the same structure. If you mean the label of the tabs this will be implemented in the future when we know what the tabs will be and where this data comes from as this is not clear atm.

2022-04-07 12:58 UTC, thomssonkarl commented on src/components/diagram/customNodes/activityNode.js
> +      ) : null}
So... what is your suggestion? The dialog popup will only be accessible from the activity nodes and there is currently no way to have more then one open at the same time.

2022-04-08 12:08 UTC, JoXW100 requested changes
Remove the unused import and make sure to format the files

2022-04-08 12:08 UTC, JoXW100 commented on src/pages/index.js
> +import DialogPopup from '../components/dialogPopup'
Remove unused import

2022-04-08 12:41 UTC, JoXW100 approved these changes

2022-04-08 15:15 UTC, mackan1410 approved these changes

2022-04-08 15:35 UTC, merged