API for interacting with a mongo database
Processillustrering/Processillustrering pull request #44
Opened 2022-04-12 14:29 UTC by Caw3

Fixes #25.

Adds the following endpoints:

`/api/graphs?filter_property=filter_value`:
- GET, gets all graphs matching a query specified in the URL. Defaults to showing all graphs
- POST, creates a new graph with the body of the request and adds it to the database

`/api/graphs/[graphId]`
- GET, gets a single graph by its id
- POST, replace a specific graph by the contents of the request body
- PATCH, update a graph with a mongo Update filter specified in the body of the request
- DELETE, deletes a single graph by its id

See `endpointMethods.js` for more info

Connect to a database by adding a file named .env.local to the root folder with the following values:
```
DB_NAME=
DB_USER=
DB_PASSWORD=
DB_IP=
DB_PORT=
CONN_SETTINGS=
MONGO_CONNSTRING=mongodb://$DB_USER:$DB_PASSWORD@$DB_IP:$DB_PORT/?$CONN_SETTINGS

```

2022-04-13 14:03 UTC, thomssonkarl approved these changes

2022-04-20 07:52 UTC, JoXW100 requested changes

2022-04-20 07:52 UTC, JoXW100 commented on src/utils/db/connector.js
> +}
normaly global mongo client promises are used for deployments, not developments. was this a mistake?

2022-04-20 07:52 UTC, JoXW100 commented on src/utils/db/mongoDatabase.js
> +    const databaseName = process.env.DB_NAME
unsure about the consequences of storing an enviroment variable like this. Its not necessary

2022-04-20 07:52 UTC, JoXW100 commented on src/utils/db/mongoDatabase.js
> +    return require('mongodb').ObjectId(id)
why requre mongodb as part of the function. store it globaly or preferably import it. This function would then not be neccesary either.

2022-04-21 14:13 UTC, JoXW100 approved these changes

2022-04-25 08:33 UTC, merged